### ISSUE TITLE
Panic on backend query when backend is not responding

### ISSUE THREAD

**Issue by chbuescher** [go-graphite/carbonapi#376]
I use carbonapi together with a go-carbon backend.
When the backend is not running, a query to carbonapi panics because variable res is nil:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xbf6f7b]

goroutine 134 [running]:
github.com/go-graphite/carbonapi/zipper/protocols/v2.(*ClientProtoV2Group).Fetch(0xc00022bce0, 0xeeaec0, 0xc0000a9140, 0xc0002ac360, 0x1, 0x1, 0xc000035060)
	/gocode/src/github.com/go-graphite/carbonapi/zipper/protocols/v2/protobuf_group.go:154 +0x9eb
github.com/go-graphite/carbonapi/zipper/broadcast.(*BroadcastGroup).doSingleFetch(0xc000255680, 0xeeaec0, 0xc0000a9140, 0xc0000a8c00, 0xef1300, 0xc00022bce0, 0xc000198058, 0x1, 0x1, 0xc0000a90e0)
	/gocode/src/github.com/go-graphite/carbonapi/zipper/broadcast/broadcast_group.go:137 +0x4d3
created by github.com/go-graphite/carbonapi/zipper/broadcast.(*BroadcastGroup).Fetch
	/gocode/src/github.com/go-graphite/carbonapi/zipper/broadcast/broadcast_group.go:215 +0x8bf

**Comment by chbuescher** [comment]
OK, I see, its already fixed ;-)
