### ISSUE TITLE
Error in parsing metric names with i18n characters

### ISSUE THREAD

**Issue by jbradleynh** [go-graphite/carbonapi#393]
We have a stack configured with go-carbon and carbonapi replacing a traditional graphite-web carbon setup. 

However we've encountered an issue where when trying to view metrics from a customer who has Kanji characters in there name is producing the following error:

```json
{
  "level": "ERROR",
  "timestamp": "2019-06-26T16:59:22.469Z",
  "logger": "access",
  "message": "request failed",
  "data": {
    "handler": "render",
    "carbonapi_uuid": "c1addb35-6ebe-49a3-97bd-e185489007fc",
    "url": "/render",
    "peer_ip": "127.0.0.1",
    "host": "localhost:8082",
    "referer": "https://grafana.example.com/grafana/d/000000002/new-view?refresh=1m&panelId=1&fullscreen&edit&orgId=1&var-customer=%E6%A0%AA%E5%BC%8F",
    "format": "json",
    "use_cache": true,
    "targets": [
      "summary.by_customer.株式.requests"
    ],
    "cache_timeout": 60,
    "runtime": 0.000422455,
    "http_code": 400,
    "reason": "Bad Request\n\nTarget              : summary.by_customer.株式.requests\nParsed so far       : summary.by_customer.\nCould not parse     : 株式.requests\n",
    "from": 1561525162,
    "until": 1561568362,
    "from_raw": "-12h",
    "until_raw": "now",
    "uri": "/render"
  }
}
```

This issue appears to be unable to parse non-ascii characters from the `/render` endpoint, however our grafana instance speaking to the `/metrics/find/` endpoint is able to pull back the customer name, in this mocked example: `株式`

**Comment by Civil** [comment]
What version you are using?

Since about this PR: https://github.com/go-graphite/carbonapi/pull/265 there is an extra config option for unicode, called `unicodeRangeTables`. I myself never used that, but to my knowledge you can add something like:
```
unicodeRangeTables:
   - japanese.EUCJP
```

and that should make your Kanji characters to be accepted by carbonapi.

However please note that I myself never used that functionality and for the config example it's better to talk to @korservick 

Also each extra unicode table will slow down parsing a bit.

**Comment by jbradleynh** [comment]
@Civil we are on version `0.10.0.1`, will investigate how to load these

**Comment by Civil** [comment]
Likely you'll need to update to at least 0.11, as I don't remember what version include that change, but I dont think it was 0.10

**Comment by Civil** [comment]
Actually I've checked and it should be included in 0.9.0 or newer, so 0.10.0.1 should be also fine.

**Comment by jbradleynh** [comment]
added the following stanza to the configuration
```
unicodeRangeTables:
  - japanese.EUCJP
  - unicode.Latin
```

and while it loads this, on 0.10.0.1 at least we're getting a panic when trying to parse the non-latin characters 

```
2019-06-27T14:27:09.994Z        INFO        main        will parse config as yaml        {"config_file": "/etc/carbonapi/carbonapi.yaml"}
2019-06-27T14:27:09.997Z        INFO        main        zipper config        {"handler": "zipper", "config": {"ConcurrencyLimitPerServer":0,"MaxIdleConnsPerHost":100,"Backends":["http://127.0.0.1:8080"],"CarbonSearch":{"Backend":"","Prefix":"virt.v1.*"},
2019-06-27T14:27:10.002Z        INFO        main        starting carbonapi        {"build_version": "0.10.0.1", "config": {"ExtrapolateExperiment":false,"Logger":[{"Logger":"","File":"stderr","Level":"info","Encoding":"json","EncodingTime":"iso8601","Enc
2019-06-27T14:27:10.008Z        INFO        main        TLD Probe run results        {"handler": "zipper", "function": "probe", "carbonzipper_uuid": "e6b1eb84-23f3-4094-8258-66235016a771", "paths_count": 2, "responses_received": 1, "backends": 1, "incomp
{"level":"INFO","timestamp":"2019-06-27T14:27:27.566Z","logger":"access","message":"request served","data":{"handler":"render","carbonapi_uuid":"67b28919-f2f5-4138-8e1c-384ecccc0362","url":"/render/?target=test.metric.nokanji.rate\u0026from=-1d\u0026unti
{"level":"INFO","timestamp":"2019-06-27T14:27:34.526Z","logger":"access","message":"request served","data":{"handler":"render","carbonapi_uuid":"7d0d92e4-62d9-46c4-99de-bbc50d79b2bb","url":"/render/?target=test.metric.株式.rate\u0026format=json\u0026from
2019/06/27 14:27:34 http: panic serving 127.0.0.1:34422: runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
net/http.(*conn).serve.func1(0xc42013b540)
        /usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0xae7a60, 0x10ebe10)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
unicode.Is(0x0, 0xc40000682a, 0x49)
        /usr/local/go/src/unicode/letter.go:159 +0x26
unicode.In(0xc40000682a, 0xc4201735d0, 0x2, 0x2, 0x1)
        /usr/local/go/src/unicode/graphic.go:71 +0x4c
github.com/go-graphite/carbonapi/pkg/parser.parseName(0xc4201c6614, 0x17, 0x77, 0xc420046870, 0x0, 0xc420046880)
        /root/go/src/github.com/go-graphite/carbonapi/pkg/parser/parser.go:581 +0x16e
github.com/go-graphite/carbonapi/pkg/parser.parseExprWithoutPipe(0xc4201c6614, 0x17, 0x1f5d480b, 0x1131520, 0x30, 0x0, 0x1131520, 0x781)
        /root/go/src/github.com/go-graphite/carbonapi/pkg/parser/parser.go:359 +0x277
github.com/go-graphite/carbonapi/pkg/parser.ParseExpr(0xc4201c6614, 0x17, 0xc420198f00, 0x0, 0xc420198f00, 0x0, 0x10fdd00, 0xc4200c7590)
        /root/go/src/github.com/go-graphite/carbonapi/pkg/parser/parser.go:381 +0x39
main.renderHandler(0x1105580, 0xc4200c2700, 0xc420194800)
        /root/go/src/github.com/go-graphite/carbonapi/http_handlers.go:262 +0xeb7
net/http.HandlerFunc.ServeHTTP(0xbc5530, 0x1105580, 0xc4200c2700, 0xc420194800)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x1131100, 0x1105580, 0xc4200c2700, 0xc420194800)
        /usr/local/go/src/net/http/server.go:2238 +0x130
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.CompressHandlerLevel.func1(0x1105580, 0xc4200c2700, 0xc420194800)
        /root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/compress.go:146 +0x17d
net/http.HandlerFunc.ServeHTTP(0xc42018c4a0, 0x1105580, 0xc4200c2700, 0xc420194800)
        /usr/local/go/src/net/http/server.go:1942 +0x44
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc420132480, 0x1105580, 0xc4200c2700, 0xc420194800)
        /root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/cors.go:51 +0xa6f
github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers.ProxyHeaders.func1(0x1105580, 0xc4200c2700, 0xc420194800)
        /root/go/src/github.com/go-graphite/carbonapi/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x117
net/http.HandlerFunc.ServeHTTP(0xc42018c4e0, 0x1105580, 0xc4200c2700, 0xc420194800)
        /usr/local/go/src/net/http/server.go:1942 +0x44
net/http.serverHandler.ServeHTTP(0xc420083d90, 0x1105580, 0xc4200c2700, 0xc420194800)
        /usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42013b540, 0x1106080, 0xc420192f00)
        /usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by Civil** [comment]
The correct section should be:
```
unicodeRangeTables:
   - "Latin"
   - "Hiragana"
   - "Katakana"
   - "Han"
```

List of supported tables:
https://golang.org/pkg/unicode/#pkg-variables, Variable called "Scripts". Or you can use unicode-alias as a name, likely capitalize first letter.

In current master I'll fix panic in case unknown table is specified.

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonapi/commit/5c5da691a79661f0408c402dfebecae808212cff

**Comment by jbradleynh** [comment]
confirmed this is working now, thanks for the quick help @Civil

**Comment by obfuscurity** [comment]
Thank you for this @Civil, I can confirm that these are working for us now. ❤️
